# Generated by Django 5.2.12 on 2026-05-08 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "recipes",
            "0011_region_bbox_east_region_bbox_north_region_bbox_south_and_more",
        ),
        ("stories", "0003_story_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="region",
            field=models.ForeignKey(
                blank=True,
                help_text="Geographic/cultural region for map discovery. Falls back to linked_recipe.region if null.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stories",
                to="recipes.region",
            ),
        ),
    ]
