# Generated by Django 5.2.12 on 2026-05-08 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "recipes",
            "0011_region_bbox_east_region_bbox_north_region_bbox_south_and_more",
        ),
        ("stories", "0004_story_region"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="summary",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="story",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="story",
            name="linked_recipe",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="linked_stories_old",
                to="recipes.recipe",
            ),
        ),
        migrations.CreateModel(
            name="StoryRecipeLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="story_links",
                        to="recipes.recipe",
                    ),
                ),
                (
                    "story",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipe_links",
                        to="stories.story",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "added_at"],
                "unique_together": {("story", "recipe")},
            },
        ),
        migrations.AddField(
            model_name="story",
            name="linked_recipes",
            field=models.ManyToManyField(
                blank=True,
                related_name="linked_stories",
                through="stories.StoryRecipeLink",
                to="recipes.recipe",
            ),
        ),
    ]
