# Generated by Django 5.2.12 on 2026-05-08 18:49

from django.db import migrations


def forwards(apps, schema_editor):
    Story = apps.get_model('stories', 'Story')
    StoryRecipeLink = apps.get_model('stories', 'StoryRecipeLink')
    for story in Story.objects.filter(linked_recipe__isnull=False):
        StoryRecipeLink.objects.get_or_create(
            story=story,
            recipe_id=story.linked_recipe_id,
            defaults={'order': 0},
        )

def backwards(apps, schema_editor):
    Story = apps.get_model('stories', 'Story')
    StoryRecipeLink = apps.get_model('stories', 'StoryRecipeLink')
    for story in Story.objects.all():
        first_link = StoryRecipeLink.objects.filter(story=story).order_by('order', 'added_at').first()
        if first_link:
            story.linked_recipe_id = first_link.recipe_id
            story.save()

class Migration(migrations.Migration):

    dependencies = [
        ("stories", "0005_story_summary_story_updated_at_and_more"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
