# Generated by Django 5.2.12 on 2026-05-08 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stories", "0006_migrate_linked_recipes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="story",
            name="linked_recipe",
        ),
    ]
