# Generated by Django 5.2.12 on 2026-05-08 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0012_religion_recipe_religions"),
        ("stories", "0007_remove_legacy_linked_recipe"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="dietary_tags",
            field=models.ManyToManyField(
                blank=True, related_name="stories", to="recipes.dietarytag"
            ),
        ),
        migrations.AddField(
            model_name="story",
            name="event_tags",
            field=models.ManyToManyField(
                blank=True, related_name="stories", to="recipes.eventtag"
            ),
        ),
        migrations.AddField(
            model_name="story",
            name="religions",
            field=models.ManyToManyField(
                blank=True, related_name="stories", to="recipes.religion"
            ),
        ),
    ]
