# Generated by Django 5.2.12 on 2026-05-10 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0009_story_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='story_type',
            field=models.CharField(blank=True, choices=[('traditional', 'Traditional'), ('historical', 'Historical'), ('family', 'Family'), ('festive', 'Festive'), ('personal', 'Personal')], max_length=20, null=True),
        ),
    ]
