# Generated by Django 5.2.12 on 2026-05-11 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0010_story_type_565'),
        ('stories', '0010_storycomment_storyvote'),
    ]

    operations = [
    ]
