# Generated by Django 5.2.12 on 2026-05-12 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0011_merge_0010_story_type_565_0010_storycomment_storyvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
