# Generated by Django 5.2.12 on 2026-05-12 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0012_story_latitude_longitude'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ['-created_at', '-id']},
        ),
    ]
