import { StyleSheet } from 'react-native';
import { shadows, tokens } from '../../theme';

export const recipeFormStyles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: tokens.colors.bg },
  scroll: { padding: 20, paddingBottom: 32 },
  card: {
    backgroundColor: tokens.colors.surface,
    borderRadius: tokens.radius.xl,
    padding: 18,
    borderWidth: 1,
    borderColor: tokens.colors.border,
    ...shadows.lg,
  },
  heading: {
    fontSize: 28,
    fontWeight: '700',
    marginBottom: 8,
    color: tokens.colors.text,
    fontFamily: tokens.typography.display.fontFamily,
  },
  lead: {
    fontSize: 16,
    color: tokens.colors.textMuted,
    marginBottom: 20,
    lineHeight: 22,
  },
  section: { marginBottom: 18 },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: tokens.colors.text,
    marginBottom: 10,
  },
  label: {
    fontSize: 14,
    fontWeight: '600',
    color: tokens.colors.text,
    marginBottom: 6,
  },
  input: {
    borderWidth: 2,
    borderColor: tokens.colors.border,
    borderRadius: tokens.radius.md,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 16,
    backgroundColor: tokens.colors.surfaceInput,
    marginBottom: 6,
    color: tokens.colors.text,
  },
  textArea: {
    borderWidth: 2,
    borderColor: tokens.colors.border,
    borderRadius: tokens.radius.md,
    paddingHorizontal: 12,
    paddingVertical: 12,
    fontSize: 16,
    backgroundColor: tokens.colors.surfaceInput,
    minHeight: 110,
    textAlignVertical: 'top',
    color: tokens.colors.text,
  },
  inputError: { borderColor: tokens.colors.error },
  errorText: { color: tokens.colors.error, fontSize: 13, marginTop: 4, marginBottom: 6 },
  rowCard: {
    borderWidth: 1,
    borderColor: tokens.colors.border,
    borderRadius: tokens.radius.lg,
    padding: 12,
    backgroundColor: tokens.colors.surface,
    marginBottom: 12,
    ...shadows.sm,
  },
  rowHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  rowTitle: { fontSize: 15, fontWeight: '700', color: tokens.colors.text },
  removeText: { color: tokens.colors.error, fontWeight: '700', fontSize: 14 },
  primaryButton: {
    backgroundColor: tokens.colors.primary,
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderRadius: tokens.radius.pill,
    alignItems: 'center',
    marginBottom: 14,
    borderWidth: 2,
    borderColor: tokens.colors.primary,
  },
  primaryButtonText: { color: tokens.colors.surface, fontSize: 16, fontWeight: '700' },
  secondaryButton: {
    borderWidth: 2,
    borderColor: tokens.colors.primary,
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderRadius: tokens.radius.pill,
    alignItems: 'center',
    backgroundColor: 'transparent',
  },
  secondaryButtonText: { color: tokens.colors.primary, fontSize: 16, fontWeight: '700' },
  buttonPressed: { opacity: 0.9 },
  videoMeta: {
    marginTop: 10,
    padding: 12,
    borderRadius: tokens.radius.lg,
    borderWidth: 1,
    borderColor: tokens.colors.border,
    backgroundColor: tokens.colors.surface,
    gap: 8,
    ...shadows.sm,
  },
  videoLine: { fontSize: 14, color: tokens.colors.text },
  videoHint: { fontSize: 14, color: tokens.colors.textMuted, marginTop: 8, lineHeight: 20 },
  summary: {
    marginTop: 8,
    padding: 14,
    borderRadius: tokens.radius.lg,
    backgroundColor: tokens.colors.primarySubtle,
    borderWidth: 1,
    borderColor: tokens.colors.primaryBorder,
  },
  summaryTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: tokens.colors.text,
    marginBottom: 8,
  },
  summaryLine: { fontSize: 15, color: tokens.colors.text, marginBottom: 4 },
});
