# Generated by Django 5.2.12 on 2026-04-30 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CulturalContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('kind', models.CharField(choices=[('tradition', 'Tradition'), ('dish', 'Dish'), ('story', 'Story'), ('fact', 'Fact'), ('holiday', 'Holiday')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('region', models.CharField(blank=True, default='', max_length=100)),
                ('link_kind', models.CharField(blank=True, choices=[('recipe', 'Recipe'), ('story', 'Story')], default='', max_length=20)),
                ('link_id', models.PositiveIntegerField(blank=True, null=True)),
                ('cultural_tags', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
