# Generated by Django 5.2.12 on 2026-05-08 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cultural_content", "0001_initial"),
        (
            "recipes",
            "0011_region_bbox_east_region_bbox_north_region_bbox_south_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="culturalcontent",
            name="region_text",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Original free-text region value (legacy / fallback).",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="culturalcontent",
            name="region",
            field=models.ForeignKey(
                blank=True,
                help_text="Structured region FK for map-discovery queries.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cultural_content",
                to="recipes.region",
            ),
        ),
    ]
