# Generated by Django 5.2.12 on 2026-05-02 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_cultural_onboarding_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_contactable",
            field=models.BooleanField(
                default=True,
                help_text="Whether other users can start new message threads with this user.",
            ),
        ),
    ]
