# Generated by Django 5.2.12 on 2026-05-08 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_is_contactable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_contactable",
            field=models.BooleanField(
                default=True,
                help_text="Whether other users can start new message threads with this user. Note: A contact-disabled user can still initiate threads outbound.",
            ),
        ),
    ]
