# Generated by Django 5.2.12 on 2026-04-07 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recipes/images/'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='recipes/videos/'),
        ),
    ]
