# Generated by Django 5.2.12 on 2026-04-07 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_image_recipe_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='qa_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
