# Generated by Django 5.2.12 on 2026-04-30 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietaryTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_approved', models.BooleanField(default=False, help_text='Moderation flag.')),
            ],
        ),
        migrations.CreateModel(
            name='EventTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_approved', models.BooleanField(default=False, help_text='Moderation flag.')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='dietary_tags',
            field=models.ManyToManyField(blank=True, related_name='recipes', to='recipes.dietarytag'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='event_tags',
            field=models.ManyToManyField(blank=True, related_name='recipes', to='recipes.eventtag'),
        ),
    ]
