# Generated by Django 5.2.12 on 2026-04-30 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0007_dietary_event_tags"),
        ("recipes", "0007_vote"),
    ]

    operations = []
