# Generated by Django 5.2.12 on 2026-05-03 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_merge_0007_dietary_event_tags_0007_vote'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientSubstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_type', models.CharField(choices=[('flavor', 'Flavor'), ('texture', 'Texture'), ('chemical', 'Chemical')], max_length=10)),
                ('closeness', models.DecimalField(decimal_places=2, max_digits=3)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_substitutions', to='recipes.ingredient')),
                ('to_ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_substitutions', to='recipes.ingredient')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('closeness__gte', 0), ('closeness__lte', 1)), name='substitution_closeness_range'), models.CheckConstraint(condition=models.Q(('from_ingredient', models.F('to_ingredient')), _negated=True), name='substitution_no_self_loop')],
                'unique_together': {('from_ingredient', 'to_ingredient', 'match_type')},
            },
        ),
    ]
