# Generated by Django 5.2.12 on 2026-05-08 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0010_seed_ingredient_substitutions"),
    ]

    operations = [
        migrations.AddField(
            model_name="region",
            name="bbox_east",
            field=models.FloatField(
                blank=True, help_text="Eastern longitude bound.", null=True
            ),
        ),
        migrations.AddField(
            model_name="region",
            name="bbox_north",
            field=models.FloatField(
                blank=True, help_text="Northern latitude bound.", null=True
            ),
        ),
        migrations.AddField(
            model_name="region",
            name="bbox_south",
            field=models.FloatField(
                blank=True, help_text="Southern latitude bound.", null=True
            ),
        ),
        migrations.AddField(
            model_name="region",
            name="bbox_west",
            field=models.FloatField(
                blank=True, help_text="Western longitude bound.", null=True
            ),
        ),
        migrations.AddField(
            model_name="region",
            name="latitude",
            field=models.FloatField(
                blank=True, help_text="Center latitude of the region.", null=True
            ),
        ),
        migrations.AddField(
            model_name="region",
            name="longitude",
            field=models.FloatField(
                blank=True, help_text="Center longitude of the region.", null=True
            ),
        ),
        migrations.AddField(
            model_name="region",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional parent region for hierarchical grouping.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="recipes.region",
            ),
        ),
    ]
