# Generated by Django 5.2.12 on 2026-05-08 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "recipes",
            "0011_region_bbox_east_region_bbox_north_region_bbox_south_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Religion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "is_approved",
                    models.BooleanField(default=False, help_text="Moderation flag."),
                ),
            ],
        ),
        migrations.AddField(
            model_name="recipe",
            name="religions",
            field=models.ManyToManyField(
                blank=True, related_name="recipes", to="recipes.religion"
            ),
        ),
    ]
