# Generated by Django 5.2.12 on 2026-05-08 19:35

from django.db import migrations


def seed_taxonomy(apps, schema_editor):
    EventTag = apps.get_model('recipes', 'EventTag')
    DietaryTag = apps.get_model('recipes', 'DietaryTag')
    Religion = apps.get_model('recipes', 'Religion')

    events = ['Wedding', 'Funeral', 'Graduation', 'Birthday', 'Anniversary', 'Religious Holiday']
    diets = ['Vegan', 'Vegetarian', 'Halal', 'Kosher', 'Gluten-Free', 'Dairy-Free']
    religions = ['Islam', 'Christianity', 'Judaism', 'Hinduism', 'Buddhism']

    for name in events:
        EventTag.objects.get_or_create(name=name, defaults={'is_approved': True})
    for name in diets:
        DietaryTag.objects.get_or_create(name=name, defaults={'is_approved': True})
    for name in religions:
        Religion.objects.get_or_create(name=name, defaults={'is_approved': True})

def clear_taxonomy(apps, schema_editor):
    EventTag = apps.get_model('recipes', 'EventTag')
    DietaryTag = apps.get_model('recipes', 'DietaryTag')
    Religion = apps.get_model('recipes', 'Religion')

    EventTag.objects.filter(name__in=['Wedding', 'Funeral', 'Graduation', 'Birthday', 'Anniversary', 'Religious Holiday']).delete()
    DietaryTag.objects.filter(name__in=['Vegan', 'Vegetarian', 'Halal', 'Kosher', 'Gluten-Free', 'Dairy-Free']).delete()
    Religion.objects.filter(name__in=['Islam', 'Christianity', 'Judaism', 'Hinduism', 'Buddhism']).delete()

class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0012_religion_recipe_religions"),
    ]

    operations = [
        migrations.RunPython(seed_taxonomy, migrations.RunPython.noop),
    ]
