# Generated by Django 5.2.12 on 2026-05-09 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_seed_taxonomy'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='density_g_per_ml',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='g per ml. Required for mass to volume conversions. See apps/recipes/conversions/references.md for cited sources.', max_digits=8, null=True),
        ),
    ]
