# Generated by Django 5.2.12 on 2026-05-09 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_ingredient_density_g_per_ml'),
        ('recipes', '0015_backfill_region_is_approved'),
    ]

    operations = [
    ]
