# Generated by Django 5.2.12 on 2026-05-10 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0019_ingredient_checkoff_529'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='heritage_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='recipe',
            name='is_heritage',
            field=models.BooleanField(default=False),
        ),
    ]
