# Generated by Django 5.2.12 on 2026-05-11 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0021_remove_secular_religion'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeCulturalContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity_note', models.TextField(blank=True, default='', help_text='Why this dish matters.')),
                ('memory_note', models.TextField(blank=True, default='', help_text='A personal memory.')),
                ('migration_note', models.TextField(blank=True, default='', help_text='Where it came from.')),
                ('ritual_note', models.TextField(blank=True, default='', help_text="When it's made.")),
                ('commensality_note', models.TextField(blank=True, default='', help_text="How it's shared.")),
                ('terroir_note', models.TextField(blank=True, default='', help_text='Taste of place.')),
                ('craft_note', models.TextField(blank=True, default='', help_text='The craft.')),
                ('recipe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cultural_context', to='recipes.recipe')),
            ],
        ),
    ]
