# Generated by Django 5.2.12 on 2026-05-11 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0021_remove_secular_religion'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waypoints', models.JSONField(blank=True, default=list, help_text='Ordered list of {lat, lng, era, label} dicts; draw order of the polyline.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='migration_routes', to='recipes.ingredient')),
            ],
        ),
    ]
