# Generated by Django 5.2.12 on 2026-05-11 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0022_zoom_region_coords_662'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='heritage_status',
            field=models.CharField(choices=[('none', 'None'), ('endangered', 'Endangered'), ('preserved', 'Preserved'), ('revived', 'Revived')], default='none', help_text='Endangered-heritage tag (#524).', max_length=16),
        ),
        migrations.AddField(
            model_name='recipe',
            name='heritage_status',
            field=models.CharField(choices=[('none', 'None'), ('endangered', 'Endangered'), ('preserved', 'Preserved'), ('revived', 'Revived')], default='none', help_text='Endangered-heritage tag (#524).', max_length=16),
        ),
        migrations.CreateModel(
            name='EndangeredNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('source_url', models.URLField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endangered_notes', to='recipes.recipe')),
            ],
        ),
    ]
