# Generated by Django 5.2.12 on 2026-05-11 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0023_endangered_heritage_tags_524"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecipeCulturalContext",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identity_note",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Why This Dish Matters (Identity connection)",
                    ),
                ),
                (
                    "memory_note",
                    models.TextField(
                        blank=True, default="", help_text="Personal memory"
                    ),
                ),
                (
                    "migration_note",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Migration/diaspora story (Where It Came From)",
                    ),
                ),
                (
                    "ritual_note",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Ritual/seasonal context (When It's Made)",
                    ),
                ),
                (
                    "commensality_note",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Table culture (How It's Shared)",
                    ),
                ),
                (
                    "terroir_note",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Terroir/geography (Taste of Place)",
                    ),
                ),
                (
                    "craft_note",
                    models.TextField(
                        blank=True, default="", help_text="Skill/mastery (The Craft)"
                    ),
                ),
                (
                    "recipe",
                    models.OneToOneField(
                        help_text="The recipe this cultural context belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cultural_context",
                        to="recipes.recipe",
                    ),
                ),
            ],
        ),
    ]
