# Generated by Django 5.2.12 on 2026-05-11 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0022_ingredient_routes_523'),
        ('recipes', '0023_endangered_heritage_tags_524'),
    ]

    operations = [
    ]
