# Generated by Django 5.2.12 on 2026-05-11 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0024_merge_20260511_2130'),
        ('recipes', '0024_merge_20260511_2135'),
        ('recipes', '0024_merge_20260511_2138'),
    ]

    operations = [
    ]
