# Generated by Django 5.2.12 on 2026-05-12 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0028_recipe_average_rating_recipe_rating_count_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-created_at', '-id']},
        ),
    ]
