# Generated by Django 5.2.12 on 2026-05-12 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0030_reseed_regions"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="meal_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("breakfast", "Breakfast"),
                    ("soup", "Soup"),
                    ("main_course", "Main Course"),
                    ("dessert", "Dessert"),
                    ("snack", "Snack"),
                    ("drink", "Drink"),
                ],
                default="",
                max_length=20,
            ),
        ),
    ]
