# Generated by Django 5.2.12 on 2026-05-10 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeritageGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HeritageGroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('heritage_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='heritage.heritagegroup')),
            ],
            options={
                'ordering': ['heritage_group', '-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='heritage_he_content_026cc1_idx')],
                'unique_together': {('heritage_group', 'content_type', 'object_id')},
            },
        ),
    ]
