# Generated by Django 5.2.12 on 2026-05-10 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heritage', '0001_initial'),
        ('recipes', '0019_ingredient_checkoff_529'),
    ]

    operations = [
        migrations.CreateModel(
            name='CulturalFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('source_url', models.URLField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('heritage_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cultural_facts', to='heritage.heritagegroup')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cultural_facts', to='recipes.region')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
