# Generated by Django 5.2.12 on 2026-05-10 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heritage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeritageJourneyStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('location', models.CharField(max_length=255)),
                ('story', models.TextField()),
                ('era', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('heritage_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journey_steps', to='heritage.heritagegroup')),
            ],
            options={
                'ordering': ['heritage_group', 'order'],
                'unique_together': {('heritage_group', 'order')},
            },
        ),
    ]
