# Generated by Django 5.2.12 on 2026-05-11 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("heritage", "0003_cultural_fact_522"),
        ("recipes", "0021_remove_secular_religion"),
    ]

    operations = [
        migrations.CreateModel(
            name="IngredientRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("waypoints", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="migration_routes",
                        to="recipes.ingredient",
                    ),
                ),
            ],
            options={
                "ordering": ["ingredient"],
            },
        ),
    ]
