# Generated by Django 5.2.12 on 2026-05-12 00:10

from django.db import migrations, models


def backfill_notification_type(apps, schema_editor):
    """Set notification_type on pre-existing rows from the message text.

    The reply-notification message contains "replied"; everything else is
    treated as a question notification (the only other path that existed).
    """
    Notification = apps.get_model('notifications', 'Notification')
    for notification in Notification.objects.all():
        message = (notification.message or '').lower()
        notification.notification_type = 'reply' if 'replied' in message else 'question'
        notification.save(update_fields=['notification_type'])


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('question', 'Question'), ('reply', 'Reply'), ('rating', 'Rating')], default='question', max_length=16),
        ),
        migrations.RunPython(backfill_notification_type, migrations.RunPython.noop),
    ]
