# Generated by Django 5.2.12 on 2026-05-12 00:05

from django.db import migrations, models


def backfill_notification_types(apps, schema_editor):
    Notification = apps.get_model('notifications', 'Notification')
    for notification in Notification.objects.all().iterator():
        message = (notification.message or '').lower()
        if 'replied to your question' in message:
            notification.notification_type = 'reply'
        elif 'asked a question on your recipe' in message:
            notification.notification_type = 'question'
        else:
            notification.notification_type = 'question'
        notification.save(update_fields=['notification_type'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('question', 'Question'), ('reply', 'Reply'), ('rating', 'Rating')], default='question', max_length=16),
        ),
        migrations.RunPython(backfill_notification_types, noop_reverse),
    ]
