# Generated by Django 5.2.12 on 2026-05-11 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passport', '0002_backfill_passports_583'),
        ('recipes', '0021_remove_secular_religion'),
        ('stories', '0010_story_type_565'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('discovery', 'Discovery'), ('heritage', 'Heritage'), ('journey', 'Journey'), ('community', 'Community')], max_length=20)),
                ('target_count', models.IntegerField(default=1)),
                ('filter_criteria', models.JSONField(blank=True, default=dict)),
                ('reward_type', models.CharField(choices=[('stamp', 'Stamp'), ('theme', 'Theme'), ('points', 'Points')], max_length=20)),
                ('reward_value', models.CharField(blank=True, default='', max_length=120)),
                ('is_event_quest', models.BooleanField(default=False)),
                ('event_start', models.DateTimeField(blank=True, null=True)),
                ('event_end', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'passport_quests',
            },
        ),
        migrations.CreateModel(
            name='PassportEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('recipe_tried', 'Recipe tried'), ('story_saved', 'Story saved'), ('stamp_earned', 'Stamp earned'), ('quest_completed', 'Quest completed'), ('heritage_shared', 'Heritage shared'), ('level_up', 'Level up')], max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField()),
                ('stamp_rarity', models.CharField(blank=True, choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('emerald', 'Emerald'), ('legendary', 'Legendary')], max_length=20, null=True)),
                ('related_recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='recipes.recipe')),
                ('related_story', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='stories.story')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passport_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'passport_events',
                'ordering': ['-timestamp', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Stamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('culture', models.CharField(help_text='Region/cuisine identifier, aligned with Region.name.', max_length=120)),
                ('category', models.CharField(choices=[('recipe', 'Recipe'), ('story', 'Story'), ('heritage', 'Heritage'), ('exploration', 'Exploration'), ('community', 'Community')], max_length=20)),
                ('rarity', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('emerald', 'Emerald'), ('legendary', 'Legendary')], default='bronze', max_length=20)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('source_recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='recipes.recipe')),
                ('source_story', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='stories.story')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passport_stamps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'passport_stamps',
                'ordering': ['-earned_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'culture', 'category'), name='uniq_stamp_user_culture_category')],
            },
        ),
        migrations.CreateModel(
            name='StampInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('culture', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('recipe', 'Recipe'), ('story', 'Story'), ('heritage', 'Heritage'), ('exploration', 'Exploration'), ('community', 'Community')], max_length=20)),
                ('kind', models.CharField(choices=[('recipe_try', 'Recipe tried'), ('story_save', 'Story saved')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='recipes.recipe')),
                ('story', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='stories.story')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passport_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'passport_stamp_interactions',
                'constraints': [models.UniqueConstraint(condition=models.Q(('recipe__isnull', False)), fields=('user', 'recipe'), name='uniq_stamp_interaction_user_recipe'), models.UniqueConstraint(condition=models.Q(('story__isnull', False)), fields=('user', 'story'), name='uniq_stamp_interaction_user_story')],
            },
        ),
        migrations.CreateModel(
            name='UserQuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.IntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('reward_claimed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_quests', to='passport.quest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passport_user_quests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'passport_user_quests',
                'constraints': [models.UniqueConstraint(fields=('user', 'quest'), name='uniq_user_quest')],
            },
        ),
    ]
