# Generated by Django 5.2.12 on 2026-05-10 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Draft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[("story", "Story"), ("recipe", "Recipe")],
                        help_text="Type of entity (e.g., 'story', 'recipe')",
                        max_length=50,
                    ),
                ),
                (
                    "target_id",
                    models.CharField(
                        blank=True,
                        help_text="public_id of the entity. Null for new creations.",
                        max_length=26,
                        null=True,
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        help_text="The serialized state of the editor/form."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drafts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("target_id__isnull", False)),
                        fields=("user", "target_type", "target_id"),
                        name="unique_draft_existing",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("target_id__isnull", True)),
                        fields=("user", "target_type"),
                        name="unique_draft_new",
                    ),
                ],
            },
        ),
    ]
